In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('Practice.csv')
df

ID    Name Department  Salary  Experience(in years)
0   1   Aditi         HR   40000                     2
1   2   Rohan         IT   55000                     4
2   3   Priya    Finance   52000                     3
3   4    Aman         IT   60000                     5
4   5  Simran  Marketing   45000                     2
5   6   Karan    Finance   58000                     4
6   7    Neha         HR   42000                     1
7   8   Vikas         IT   67000                     6
8   9    Riya  Marketing   47000                     3
9  10   Arjun    Finance   61000                     5

## 1. Print first 5 rows

In [21]:
df.head()


ID    Name Department  Salary  Experience(in years)
0   1   Aditi         HR   40000                     2
1   2   Rohan         IT   55000                     4
2   3   Priya    Finance   52000                     3
3   4    Aman         IT   60000                     5
4   5  Simran  Marketing   45000                     2

## 2. Show total number of rows and columns

In [22]:
df.shape

(10, 5)


## 3. Display only Name and Salary columns


In [23]:
df[["Name", "Salary"]]


Name  Salary
0   Aditi   40000
1   Rohan   55000
2   Priya   52000
3    Aman   60000
4  Simran   45000
5   Karan   58000
6    Neha   42000
7   Vikas   67000
8    Riya   47000
9   Arjun   61000

## 4. Find the average salary

In [24]:
df["Salary"].mean()

np.float64(52700.0)

## 5. Get all records where department is "IT"

In [25]:
df[df['Department']=='IT']

ID   Name Department  Salary  Experience(in years)
1   2  Rohan         IT   55000                     4
3   4   Aman         IT   60000                     5
7   8  Vikas         IT   67000                     6

# 6. Sort the data by salary in descending order

In [26]:
df.sort_values(by="Salary",ascending=False)

ID    Name Department  Salary  Experience(in years)
7   8   Vikas         IT   67000                     6
9  10   Arjun    Finance   61000                     5
3   4    Aman         IT   60000                     5
5   6   Karan    Finance   58000                     4
1   2   Rohan         IT   55000                     4
2   3   Priya    Finance   52000                     3
8   9    Riya  Marketing   47000                     3
4   5  Simran  Marketing   45000                     2
6   7    Neha         HR   42000                     1
0   1   Aditi         HR   40000                     2

## 7. Find min and max salary


In [27]:
df["Salary"].min(),df["Salary"].max()

(np.int64(40000), np.int64(67000))

# 8. Count how many employees are in each department

In [28]:
df["Department"].value_counts()

Department
IT           3
Finance      3
HR           2
Marketing    2
Name: count, dtype: int64

## 9. Filter employees with experience > 3 years

In [29]:
df[df['Experience(in years)']>3]

ID   Name Department  Salary  Experience(in years)
1   2  Rohan         IT   55000                     4
3   4   Aman         IT   60000                     5
5   6  Karan    Finance   58000                     4
7   8  Vikas         IT   67000                     6
9  10  Arjun    Finance   61000                     5

## 10. Add a Bonus column (10% of salary)

In [30]:
df["Bonus"] = df["Salary"] * 0.10
df

ID    Name Department  Salary  Experience(in years)   Bonus
0   1   Aditi         HR   40000                     2  4000.0
1   2   Rohan         IT   55000                     4  5500.0
2   3   Priya    Finance   52000                     3  5200.0
3   4    Aman         IT   60000                     5  6000.0
4   5  Simran  Marketing   45000                     2  4500.0
5   6   Karan    Finance   58000                     4  5800.0
6   7    Neha         HR   42000                     1  4200.0
7   8   Vikas         IT   67000                     6  6700.0
8   9    Riya  Marketing   47000                     3  4700.0
9  10   Arjun    Finance   61000                     5  6100.0

## 11. Group by Department and find average salary

In [31]:
df.groupby('Department')['Salary'].mean()

Department
Finance      57000.000000
HR           41000.000000
IT           60666.666667
Marketing    46000.000000
Name: Salary, dtype: float64

In [32]:
print(df['Salary'].memory_usage(deep=True))
df['Salary'] = df['Salary'].astype('category')
print(f"Optimized 'grade' dtype: {df['Salary'].dtype}")
print(df['Salary'].memory_usage(deep=True))

212
Optimized 'grade' dtype: category
522


In [33]:
salaryy = df['Salary'].to_numpy()
salaryy

array([40000, 55000, 52000, 60000, 45000, 58000, 42000, 67000, 47000,
       61000])

In [34]:
import numpy as np
min_sal = df['Salary'].min()
max_sal = df['Salary'].max()

salary = np.linspace(min_sal,max_sal,5)
print(salary)


TypeError: Categorical is not ordered for operation min
you can use .as_ordered() to change the Categorical to an ordered one


In [ ]:
num_std = len(df)
attendence = np.zeros(num_std,dtype=int)
attendence

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 🟢 PART 1: Pandas Questions

In [36]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Kunal", "Neha", "Arjun", "Priya", "Rohit", "Simran"],
    "Math": [78, 85, 62, 90, 55, 88, 70, 95],
    "Science": [72, 80, 60, 92, 58, 85, 68, 90],
    "English": [75, 82, 65, 88, 60, 90, 72, 94],
    "Attendance": [85, 92, 78, 95, 70, 90, 88, 96]
}

df = pd.DataFrame(data)
print(df)

     Name  Math  Science  English  Attendance
0    Aman    78       72       75          85
1    Riya    85       80       82          92
2   Kunal    62       60       65          78
3    Neha    90       92       88          95
4   Arjun    55       58       60          70
5   Priya    88       85       90          90
6   Rohit    70       68       72          88
7  Simran    95       90       94          96


### Q1️⃣ Print first 5 rows of the dataset

In [ ]:
df.head()

Name  Math  Science  English  Attendance
0   Aman    78       72       75          85
1   Riya    85       80       82          92
2  Kunal    62       60       65          78
3   Neha    90       92       88          95
4  Arjun    55       58       60          70

### Q2️⃣ Add a new column Total_Marks

In [37]:
df['Total_Marks'] = df[['Math','Science','English']].sum(axis=1)
df


Name  Math  Science  English  Attendance  Total_Marks
0    Aman    78       72       75          85          225
1    Riya    85       80       82          92          247
2   Kunal    62       60       65          78          187
3    Neha    90       92       88          95          270
4   Arjun    55       58       60          70          173
5   Priya    88       85       90          90          263
6   Rohit    70       68       72          88          210
7  Simran    95       90       94          96          279

### Q3️⃣ Add another column Average_Marks

In [38]:
df['Avg_marks'] = df[['Math','Science','English']].mean(axis=1)
df

Name  Math  Science  English  Attendance  Total_Marks  Avg_marks
0    Aman    78       72       75          85          225  75.000000
1    Riya    85       80       82          92          247  82.333333
2   Kunal    62       60       65          78          187  62.333333
3    Neha    90       92       88          95          270  90.000000
4   Arjun    55       58       60          70          173  57.666667
5   Priya    88       85       90          90          263  87.666667
6   Rohit    70       68       72          88          210  70.000000
7  Simran    95       90       94          96          279  93.000000

### Q4️⃣ Find the topper (highest total marks)

In [39]:
highest = df['Total_Marks'].max()
highest

np.int64(279)

### Q5️⃣ Print students who scored more than 85 average marks

In [40]:
above85 = df[df['Avg_marks'] > 85]
above85

Name  Math  Science  English  Attendance  Total_Marks  Avg_marks
3    Neha    90       92       88          95          270  90.000000
5   Priya    88       85       90          90          263  87.666667
7  Simran    95       90       94          96          279  93.000000

### Q6️⃣ Find the average marks in each subject

In [41]:
Avg_marks_each = df[['Math','Science','English']].mean(axis=0)
Avg_marks_each

Math       77.875
Science    75.625
English    78.250
dtype: float64

### Q7️⃣ Count how many students have attendance < 80%

In [42]:
count_att = df['Attendance']<80
count_att.sum()

np.int64(2)

### Q8️⃣ Sort students by Total_Marks (highest first)

In [43]:
df_sorted = df.sort_values(by='Total_Marks')
df_sorted


Name  Math  Science  English  Attendance  Total_Marks  Avg_marks
4   Arjun    55       58       60          70          173  57.666667
2   Kunal    62       60       65          78          187  62.333333
6   Rohit    70       68       72          88          210  70.000000
0    Aman    78       72       75          85          225  75.000000
1    Riya    85       80       82          92          247  82.333333
5   Priya    88       85       90          90          263  87.666667
3    Neha    90       92       88          95          270  90.000000
7  Simran    95       90       94          96          279  93.000000

## 🔵 PART 2: NumPy Questions

In [44]:
import numpy as np

marks = df[["Math", "Science", "English"]].values
marks

array([[78, 72, 75],
       [85, 80, 82],
       [62, 60, 65],
       [90, 92, 88],
       [55, 58, 60],
       [88, 85, 90],
       [70, 68, 72],
       [95, 90, 94]])

### Q9️⃣ Find:

Maximum marks

Minimum marks

Mean marks

In [ ]:
np.max(marks)
np.min(marks)
np.mean(marks)

np.float64(77.25)

### Q🔟 Find subject-wise average using axis

In [49]:
import numpy as np

Marks = df[['Math', 'Science', 'English']].values  # convert to NumPy array

# Subject-wise average (column-wise)
avg_subjects = np.mean(Marks, axis=0)  

# Student-wise average (row-wise)
avg_students = np.mean(Marks, axis=1)

avg_students
avg_subjects


array([77.875, 75.625, 78.25 ])

### Q1️⃣1️⃣ Find students whose Math marks < class average

In [ ]:
less_marks = 